sudo: required
services:
  - docker

before_install:
  - docker build -t joeybmercs/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true joeybmercs/docker-react npm run test
#  - docker run joeybmercs/docker-react npm run test -- --coverage

language: generic 

